---
title: "group_project"
author: "He Jin"
date: "10/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ElemStatLearn)
library(gbm)
library(randomForest)
library(tidyverse)
library(ranger)

```

# spam data
```{r}
PD = spam
ind = read.delim("spam.traintest.txt", header = F)
data = cbind(PD, ind)

XTraining = data %>% 
  filter(V1 == 0) %>% 
  mutate(Y = spam) %>% 
  select(-spam, -V1)

p = dim(XTraining)[2] - 1 

XTesting = data %>% 
  filter(V1 == 1) %>% 
  mutate(Y = spam) %>% 
  select(-spam, -V1)
```

```{r}
terms = paste( colnames(XTraining)[1:p], collapse = "+" ) # dont consider the last column (the response variable)
formula = formula( paste( colnames(XTraining)[p + 1], " ~ ", terms ) )
n_trees = 500
```

```{r}
if( TRUE ){ 
    library(randomForest)

    XTraining[,58] = factor(XTraining[,58])
    XTesting[,58] = factor(XTesting[,58])

    rf_test_error = matrix( 0, nrow=n_trees, ncol=1 ) 
    rf_oob_error = matrix( 0, nrow=n_trees, ncol=1 ) 
    for( nti in seq(1,n_trees) ){
      if( nti %% 25 == 0 ){
        print(sprintf("Building Random Forest with %5d Trees %5.2f %% done ... ", nti, nti/n_trees))
      }
      rf = randomForest( formula, data=XTraining, ntree=nti ) #mtry, nodesize
      rf_test_error[nti] = 1 - mean( predict( rf, XTesting[,1:p] ) == XTesting[,p+1] )
      rf_oob_error[nti] = mean(rf$err.rate[,1])
    }

plot( seq(1,n_trees), rf_test_error, ylim=c(0.04,0.07), type="l", col="red" )
#    save(rf_test_error, file="chap_15_rf_spam.RData")
}
#else{
  load("chap_15_rf_spam.RData")
```

```{r}
plot( seq(1,n_trees), rf_test_error, ylim=c(0.04,0.1), type="l", col="red", xlab="Number of Trees", ylab="Misclassification Error", main="Spam Data" )
lines( seq(1,n_trees), rf_oob_error, ylim=c(0.04,0.1), type="l", col="green", xlab="Number of Trees", ylab="OOB Error", main="Spam Data" )
legend(200, 0.1, c("Test Error", "OOB Error"), col=c("red", "green"), lty=c(1,1) )

save.image()
```






```{r}
library(randomForest)
rf = randomForest(formula, data = XTraining, ntree = nti) #mtry, nodesize
rf_test_error[nti] = 1 - mean( predict( rf, XTesting[,1:p] ) == XTesting[, p + 1])
```





